services:
  
  mybackendservice:
    image:  sudankhanal/firstdeployment:latest
    restart: always
    environment:
      PORT: 5000
      NODE_ENV: production

    expose: 
      - "5000"

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - '80:80' 
      - '443:443'   

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

